### PR TITLE
check ref before grouping

### PR DESCRIPTION
**Pull request by Shackmeister**
Not sure why the original code didn't work, so this might be more of a workaround than an actual fix.
If I have some time, I'll make a bugreport on GItlab for the upstream version

### CODE REVIEW

**Comment by matthewlai** [comment]
The original code doesn't work because the comp class's eq operator implementation only checks value and footprint. Can you make the change there instead?

https://github.com/matthewlai/JLCKicadTools/blob/6e19b39dea3fa3014f29e1715333116c6c34c6ad/jlc_kicad_tools/jlc_lib/kicad_netlist_reader.py#L338

**Comment by Shackmeister** [comment]
oh thats right. Thanks!
Should be fixed there now

**Comment by matthewlai** [comment]
Thanks!

**Comment by Shackmeister** [comment]
NP, and thanks for the assistance.
I should probably get back to ordering my board :D

**Comment by matthewlai** [comment]
Good luck with that!

**Comment by Shackmeister** [comment]
Fixed in Kicad master https://gitlab.com/kicad/code/kicad/-/commit/9ca61b50b6beb385b5b80c4bd5eae055b1609e7d

**Pull request merged**
