### PR TITLE
changed all instances of "netlist" to "bom"

### PR DESCRIPTION
**Pull request by Shackmeister**
The required file is a bom file, and not a netlist file

### CODE REVIEW

**Comment by matthewlai** [comment]
It is actually a netlist file. It's a netlist file in a common format (not the format Pcbnew takes) that plugins use to generate BOMs from. That's why you can generate BOMs in any format and it will work, because it will trigger the netlist to be generated. As far as I know there is no easy way to only generate the netlist.

**Comment by Shackmeister** [comment]
Thats actually true, I just went into EEschema and generated a "PCBnew" netlist :) 
Is there another term more in line of Kicad's terminology?
(unless I'm the only one who has gotten confused over it)

**Comment by matthewlai** [comment]
Yeah it's pretty confusing :(. That's actually what I did at first, too. KiCad calls it a netlist, but it's not supposed to be a public format. It's only supposed to be used internally (by BOM plugin writers to generate BOMs from). Would be nice if we can use the Pcbnew netlist, but I'm not sure if it has all the information we need, and there's also no existing script to parse it (KiCad included the XML "netlist" parsing script to help people write BOM plugins).

**Comment by matthewlai** [comment]
I added a comment in the error. Hopefully that makes it clearer. https://github.com/matthewlai/JLCKicadTools/commit/6e19b39dea3fa3014f29e1715333116c6c34c6ad

**Pull request closed without merging**
