### PR TITLE
Move dependency requirements to setup.py from requirements.txt

### PR DESCRIPTION
**Pull request by kroesche**
PR made in response to https://github.com/matthewlai/JLCKicadTools/issues/72

I added the requirements for external dependency to setup.py and deleted requirements.txt. I set the version to >= 1.5, as you had it pinned to 1.5.0 in the requirements file. If there is some reason it must be 1.5.0 and cannot be more recent (such as the current 1.7) then this will need to be changed.

### CODE REVIEW

**Comment by sophiekovalevsky** [comment]
@kroesche thanks. I tested here and works well. One tiny detail would be to fix ci errors. Once that is done I'll merge.

**Comment by kroesche** [comment]
Okay I will try to address CI error.

**Comment by kroesche** [comment]
I ran the CI in my fork this time and I believe it is now passing.

**Comment by sophiekovalevsky** [comment]
@kroesche thanks.

**Pull request merged**
