### PR TITLE
Fix orientation for SOD-123 Diodes

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by matthewlai** [comment]
Are you sure about this one? I have a board assembled using that footprint and it works...

**Comment by Shackmeister** [comment]
This is what I get with that setting, just tested on 2 boards
Screenshot from 2020-05-06 00-03-43

**Comment by TobleMiner** [comment]
I suggest merging #22 in favor of this PR since JLC seems to have changed orientation for all 2 terminal diode packages.

**Comment by matthewlai** [comment]
Merging #22 instead since it covers other diode packages, too. Thanks all!

**Pull request closed without merging**
